language: node_js
node_js:
  - 10.15
branches:
  only: 
    - APP_BASE
    - /^v.*$/
install:
  - yarn
os:
  - linux
  - osx

jobs:
 include:
    - stage: lint
      script: yarn lint
      
    - stage: deploy
      if: type != pull_request
      script: yarn deploy

stages:
  - lint
  - deploy