name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn workspace @yw/web install 
      - run: yarn workspace @yw/web lint
      - run: yarn workspace @yw/web tsc
      - run: yarn workspace @yw/web build
